name: engg3130
channels:
- !!python/unicode
  'anaconda'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'curl=7.49.0=1'
- !!python/unicode
  'cython=0.25.2=py27_0'
- !!python/unicode
  'hdf4=4.2.11=0'
- !!python/unicode
  'hdf5=1.8.17=1'
- !!python/unicode
  'libnetcdf=4.4.1=0'
- !!python/unicode
  'netcdf4=1.2.4=np111py27_0'
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'python=2.7.11=0'
- !!python/unicode
  'wget=2.2=py27_0'
- !!python/unicode
  'alabaster=0.7.9=py27_0'
- !!python/unicode
  'babel=2.3.4=py27_0'
- !!python/unicode
  'backports.shutil_get_terminal_size=1.0.0=py27_1'
- !!python/unicode
  'backports_abc=0.5=py27_0'
- !!python/unicode
  'blas=1.1=openblas'
- !!python/unicode
  'ca-certificates=2016.9.26=0'
- !!python/unicode
  'cairo=1.14.6=0'
- !!python/unicode
  'certifi=2016.9.26=py27_0'
- !!python/unicode
  'configparser=3.5.0=py27_0'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'decorator=4.0.10=py27_0'
- !!python/unicode
  'docutils=0.12=py27_0'
- !!python/unicode
  'entrypoints=0.2.2=py27_0'
- !!python/unicode
  'enum34=1.1.6=py27_1'
- !!python/unicode
  'fontconfig=2.11.1=6'
- !!python/unicode
  'freetype=2.6.3=1'
- !!python/unicode
  'functools32=3.2.3.2=py27_1'
- !!python/unicode
  'gettext=0.19.7=1'
- !!python/unicode
  'glib=2.51.0=2'
- !!python/unicode
  'harfbuzz=1.3.4=0'
- !!python/unicode
  'icu=56.1=4'
- !!python/unicode
  'imagesize=0.7.1=py27_0'
- !!python/unicode
  'ipykernel=4.5.2=py27_0'
- !!python/unicode
  'ipython=5.1.0=py27_2'
- !!python/unicode
  'ipython_genutils=0.1.0=py27_0'
- !!python/unicode
  'ipywidgets=5.2.2=py27_2'
- !!python/unicode
  'jinja2=2.8=py27_1'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'jsonschema=2.5.1=py27_0'
- !!python/unicode
  'jupyter_client=4.4.0=py27_0'
- !!python/unicode
  'jupyter_console=5.0.0=py27_0'
- !!python/unicode
  'jupyter_core=4.2.1=py27_0'
- !!python/unicode
  'libffi=3.2.1=3'
- !!python/unicode
  'libiconv=1.14=4'
- !!python/unicode
  'libpng=1.6.28=0'
- !!python/unicode
  'libsodium=1.0.10=0'
- !!python/unicode
  'libtiff=4.0.6=7'
- !!python/unicode
  'libxml2=2.9.4=3'
- !!python/unicode
  'markupsafe=0.23=py27_1'
- !!python/unicode
  'matplotlib=1.5.3=np111py27_5'
- !!python/unicode
  'mistune=0.7.3=py27_0'
- !!python/unicode
  'nbconvert=4.2.0=py27_0'
- !!python/unicode
  'nbformat=4.2.0=py27_0'
- !!python/unicode
  'nbstripout=0.2.9=py27_0'
- !!python/unicode
  'ncurses=5.9=10'
- !!python/unicode
  'networkx=1.11=py27_0'
- !!python/unicode
  'notebook=4.3.1=py27_0'
- !!python/unicode
  'numpy=1.11.3=py27_blas_openblas_200'
- !!python/unicode
  'openblas=0.2.19=0'
- !!python/unicode
  'pandas=0.19.2=np111py27_1'
- !!python/unicode
  'pango=1.40.3=0'
- !!python/unicode
  'pathlib2=2.1.0=py27_0'
- !!python/unicode
  'patsy=0.4.1=py27_0'
- !!python/unicode
  'pcre=8.39=0'
- !!python/unicode
  'pexpect=4.2.1=py27_0'
- !!python/unicode
  'pickleshare=0.7.3=py27_0'
- !!python/unicode
  'pip=9.0.1=py27_0'
- !!python/unicode
  'pixman=0.34.0=0'
- !!python/unicode
  'prompt_toolkit=1.0.9=py27_0'
- !!python/unicode
  'ptyprocess=0.5.1=py27_0'
- !!python/unicode
  'pygments=2.1.3=py27_1'
- !!python/unicode
  'pyparsing=2.1.10=py27_0'
- !!python/unicode
  'pyqt=4.11.4=py27_2'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2016.10=py27_0'
- !!python/unicode
  'pyzmq=16.0.2=py27_0'
- !!python/unicode
  'qt=4.8.7=3'
- !!python/unicode
  'qtconsole=4.2.1=py27_1'
- !!python/unicode
  'readline=6.2=0'
- !!python/unicode
  'requests=2.12.4=py27_0'
- !!python/unicode
  'scipy=0.18.1=np111py27_blas_openblas_201'
- !!python/unicode
  'seaborn=0.7.1=py27_0'
- !!python/unicode
  'setuptools=32.3.1=py27_0'
- !!python/unicode
  'simplegeneric=0.8.1=py27_0'
- !!python/unicode
  'singledispatch=3.4.0.3=py27_0'
- !!python/unicode
  'sip=4.18=py27_1'
- !!python/unicode
  'six=1.10.0=py27_1'
- !!python/unicode
  'snowballstemmer=1.2.1=py27_0'
- !!python/unicode
  'sphinx=1.5.1=py27_0'
- !!python/unicode
  'sqlite=3.13.0=1'
- !!python/unicode
  'ssl_match_hostname=3.5.0.1=py27_0'
- !!python/unicode
  'statsmodels=0.6.1=np111py27_0'
- !!python/unicode
  'terminado=0.6=py27_0'
- !!python/unicode
  'tk=8.5.19=1'
- !!python/unicode
  'tornado=4.4.2=py27_0'
- !!python/unicode
  'traitlets=4.3.1=py27_0'
- !!python/unicode
  'wcwidth=0.1.7=py27_0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'widgetsnbextension=1.2.6=py27_3'
- !!python/unicode
  'xz=5.2.2=0'
- !!python/unicode
  'zeromq=4.1.5=0'
- !!python/unicode
  'zlib=1.2.8=3'
- !!python/unicode
  'jupyter=1.0.0=py27_3'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'system=5.8=2'
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - prompt-toolkit==1.0.9
prefix: !!python/unicode '/export/home/users/clopezar/.conda/envs/engg3130'

